"use client";

import { FormEvent, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Building2, KeyRound, Plus, Power, Smartphone, Users, WalletCards, X } from "lucide-react";
import { Shell } from "@/components/shell";
import { api } from "@/lib/api";

type Organization = { id: string; name: string; slug: string; isActive: boolean; createdAtUtc: string; users: number; devices: number; wallets: number };
export default function PlatformPage() {
  const client = useQueryClient(); const [open, setOpen] = useState(false);
  const organizations = useQuery({ queryKey: ["organizations"], queryFn: () => api<Organization[]>("/api/platform/organizations") });
  const create = useMutation({ mutationFn: (body: object) => api("/api/platform/organizations", { method: "POST", body: JSON.stringify(body) }), onSuccess: () => { setOpen(false); client.invalidateQueries({ queryKey: ["organizations"] }); } });
  const toggle = useMutation({ mutationFn: ({ id, enabled }: { id: string; enabled: boolean }) => api(`/api/platform/organizations/${id}/status`, { method: "PUT", body: JSON.stringify({ enabled }) }), onSuccess: () => client.invalidateQueries({ queryKey: ["organizations"] }) });
  const reset = useMutation({ mutationFn: ({ id, ownerEmail, newPassword }: { id: string; ownerEmail: string; newPassword: string }) => api(`/api/platform/organizations/${id}/reset-owner-password`, { method: "POST", body: JSON.stringify({ ownerEmail, newPassword }) }) });
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); create.mutate({ name: form.get("company"), slug: form.get("slug") || null, ownerName: form.get("owner"), ownerEmail: form.get("email"), ownerPassword: form.get("password") }); }
  function resetOwner(organization: Organization) { const ownerEmail = window.prompt(`Owner email for ${organization.name}:`); if (!ownerEmail) return; const newPassword = window.prompt("New temporary password (at least 8 characters):"); if (newPassword) reset.mutate({ id: organization.id, ownerEmail, newPassword }, { onSuccess: () => window.alert("Owner password reset; prior sessions will be revoked."), onError: (error) => window.alert(error.message) }); }
  return <Shell><div className="page-head"><div><span className="eyebrow">Platform administration</span><h1>Client organizations</h1><p>Create isolated client workspaces, suspend service, and assist owners with secure account recovery.</p></div><button className="btn" onClick={() => setOpen(true)}><Plus size={18}/>Create client</button></div>
    {organizations.error && <div className="error">{organizations.error.message}</div>}<div className="stats"><div className="stat"><Building2/><span>Total clients</span><strong>{organizations.data?.length ?? 0}</strong></div><div className="stat"><Power/><span>Active clients</span><strong>{(organizations.data ?? []).filter((item) => item.isActive).length}</strong></div><div className="stat"><Smartphone/><span>Registered devices</span><strong>{(organizations.data ?? []).reduce((sum, item) => sum + item.devices, 0)}</strong></div><div className="stat"><WalletCards/><span>Managed wallets</span><strong>{(organizations.data ?? []).reduce((sum, item) => sum + item.wallets, 0)}</strong></div></div>
    <div className="grid">{(organizations.data ?? []).map((organization) => <article className="card" key={organization.id}><div className="card-top"><div className="card-icon"><Building2/></div><span className={`badge ${organization.isActive ? "success" : "danger"}`}>{organization.isActive ? "Active" : "Suspended"}</span></div><h2>{organization.name}</h2><p>Workspace: {organization.slug}</p><div className="button-row card-metrics"><span className="badge"><Users size={12}/>{organization.users} users</span><span className="badge"><Smartphone size={12}/>{organization.devices} devices</span><span className="badge"><WalletCards size={12}/>{organization.wallets} wallets</span></div><div className="button-row"><button className={`btn btn-small ${organization.isActive ? "btn-danger" : ""}`} onClick={() => toggle.mutate({ id: organization.id, enabled: !organization.isActive })}><Power size={14}/>{organization.isActive ? "Suspend" : "Reactivate"}</button><button className="btn btn-secondary btn-small" onClick={() => resetOwner(organization)}><KeyRound size={14}/>Reset owner password</button></div></article>)}</div>
    {open && <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="modal-head"><h2>Create client workspace</h2><button type="button" className="icon-button" onClick={() => setOpen(false)} aria-label="Close"><X/></button></div><div className="form-grid"><label>Company name<input name="company" required placeholder="Acme Trading"/></label><label>Workspace slug<input name="slug" placeholder="acme-trading"/></label><label>First owner name<input name="owner" required/></label><label>Owner email<input name="email" type="email" required/></label><label className="full">Temporary owner password<input name="password" type="password" minLength={8} required/><span className="muted">At least eight characters with a letter and number.</span></label></div>{create.error && <div className="error">{create.error.message}</div>}<div className="button-row" style={{ marginTop: 18 }}><button className="btn" disabled={create.isPending}>Create client and owner</button><button type="button" className="btn btn-secondary" onClick={() => setOpen(false)}>Cancel</button></div></form></div>}
  </Shell>;
}
