"use client";

import { FormEvent, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Building2, CalendarClock, KeyRound, Plus, Power, ShieldCheck, Smartphone, Trash2, Users, WalletCards, X } from "lucide-react";
import { Shell } from "@/components/shell";
import { api } from "@/lib/api";

type Organization = { id: string; name: string; slug: string; isActive: boolean; subscriptionStartsAtUtc?: string; subscriptionEndsAtUtc?: string; createdAtUtc: string; users: number; devices: number; wallets: number };
type PlatformAdmin = { id: string; displayName: string; email: string; isActive: boolean; createdAtUtc: string };

function subscriptionState(organization: Organization) {
  if (!organization.subscriptionEndsAtUtc) return { label: "Awaiting activation", className: "warning" };
  if (new Date(organization.subscriptionEndsAtUtc) <= new Date()) return { label: "Subscription expired", className: "danger" };
  return { label: "Subscription active", className: "success" };
}

function remainingDays(end?: string) {
  if (!end) return 0;
  return Math.max(0, Math.ceil((new Date(end).getTime() - Date.now()) / 86_400_000));
}

export default function PlatformPage() {
  const client = useQueryClient();
  const [createOpen, setCreateOpen] = useState(false);
  const [adminOpen, setAdminOpen] = useState(false);
  const organizations = useQuery({ queryKey: ["organizations"], queryFn: () => api<Organization[]>("/api/platform/organizations") });
  const administrators = useQuery({ queryKey: ["platform-administrators"], queryFn: () => api<PlatformAdmin[]>("/api/platform/administrators") });
  const refresh = () => client.invalidateQueries({ queryKey: ["organizations"] });
  const create = useMutation({ mutationFn: (body: object) => api("/api/platform/organizations", { method: "POST", body: JSON.stringify(body) }), onSuccess: () => { setCreateOpen(false); refresh(); } });
  const createAdmin = useMutation({ mutationFn: (body: object) => api("/api/platform/administrators", { method: "POST", body: JSON.stringify(body) }), onSuccess: () => { setAdminOpen(false); client.invalidateQueries({ queryKey: ["platform-administrators"] }); } });
  const toggle = useMutation({ mutationFn: ({ id, enabled }: { id: string; enabled: boolean }) => api(`/api/platform/organizations/${id}/status`, { method: "PUT", body: JSON.stringify({ enabled }) }), onSuccess: refresh });
  const subscription = useMutation({ mutationFn: ({ id, active, days }: { id: string; active: boolean; days?: number }) => api(`/api/platform/organizations/${id}/subscription`, { method: "PUT", body: JSON.stringify({ active, days }) }), onSuccess: refresh });
  const remove = useMutation({ mutationFn: ({ id, confirmation }: { id: string; confirmation: string }) => api(`/api/platform/organizations/${id}`, { method: "DELETE", body: JSON.stringify({ confirmation }) }), onSuccess: refresh });
  const reset = useMutation({ mutationFn: ({ id, ownerEmail, newPassword }: { id: string; ownerEmail: string; newPassword: string }) => api(`/api/platform/organizations/${id}/reset-owner-password`, { method: "POST", body: JSON.stringify({ ownerEmail, newPassword }) }) });

  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); create.mutate({ name: form.get("company"), slug: form.get("slug") || null, ownerName: form.get("owner"), ownerEmail: form.get("email"), ownerPassword: form.get("password"), activationDays: Number(form.get("days")) }); }
  function submitAdmin(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); createAdmin.mutate({ displayName: form.get("name"), email: form.get("email"), password: form.get("password") }); }
  function activate(organization: Organization) { const value = window.prompt(`Activate ${organization.name} for how many days?`, "30"); if (!value) return; const days = Number(value); if (!Number.isInteger(days) || days < 1 || days > 3650) { window.alert("Enter a whole number from 1 to 3650."); return; } subscription.mutate({ id: organization.id, active: true, days }); }
  function resetOwner(organization: Organization) { const ownerEmail = window.prompt(`Owner email for ${organization.name}:`); if (!ownerEmail) return; const newPassword = window.prompt("New temporary password (at least 8 characters):"); if (newPassword) reset.mutate({ id: organization.id, ownerEmail, newPassword }, { onSuccess: () => window.alert("Owner password reset; prior sessions will be revoked."), onError: (error) => window.alert(error.message) }); }
  function permanentlyDelete(organization: Organization) { const confirmation = window.prompt(`This permanently deletes ${organization.name}, including users, wallets, devices, and payment history.\n\nType the exact customer name to continue:`); if (confirmation === null) return; remove.mutate({ id: organization.id, confirmation }, { onError: (error) => window.alert(error.message) }); }

  return <Shell>
    <div className="page-head"><div><span className="eyebrow">Active Cash administration</span><h1>Customers & subscriptions</h1><p>Create customers, control exact subscription periods, suspend access, and permanently remove customer data.</p></div><div className="button-row"><button className="btn btn-secondary" onClick={() => setAdminOpen(true)}><ShieldCheck size={18}/>Add administrator</button><button className="btn" onClick={() => setCreateOpen(true)}><Plus size={18}/>Create customer</button></div></div>
    {(organizations.error || administrators.error) && <div className="error">{organizations.error?.message ?? administrators.error?.message}</div>}
    <div className="stats"><div className="stat"><Building2/><span>Total customers</span><strong>{organizations.data?.length ?? 0}</strong></div><div className="stat"><CalendarClock/><span>Active subscriptions</span><strong>{(organizations.data ?? []).filter((item) => item.subscriptionEndsAtUtc && new Date(item.subscriptionEndsAtUtc) > new Date()).length}</strong></div><div className="stat"><Smartphone/><span>Registered devices</span><strong>{(organizations.data ?? []).reduce((sum, item) => sum + item.devices, 0)}</strong></div><div className="stat"><ShieldCheck/><span>Platform admins</span><strong>{administrators.data?.length ?? 0}</strong></div></div>
    <div className="grid platform-customer-grid">{(organizations.data ?? []).map((organization) => { const state = subscriptionState(organization); return <article className="card customer-card" key={organization.id}><div className="card-top"><div className="card-icon"><Building2/></div><div className="customer-badges"><span className={`badge ${organization.isActive ? "success" : "danger"}`}>{organization.isActive ? "Account enabled" : "Suspended"}</span><span className={`badge ${state.className}`}>{state.label}</span></div></div><h2>{organization.name}</h2><p>Workspace: {organization.slug}</p><div className="subscription-period"><CalendarClock size={18}/><div><span>Activation period</span><strong>{organization.subscriptionEndsAtUtc ? `${remainingDays(organization.subscriptionEndsAtUtc)} days remaining` : "Not activated yet"}</strong>{organization.subscriptionEndsAtUtc && <small>Ends {new Date(organization.subscriptionEndsAtUtc).toLocaleString()}</small>}</div></div><div className="button-row card-metrics"><span className="badge"><Users size={12}/>{organization.users} users</span><span className="badge"><Smartphone size={12}/>{organization.devices} devices</span><span className="badge"><WalletCards size={12}/>{organization.wallets} wallets</span></div><div className="customer-actions"><button className="btn btn-small" onClick={() => activate(organization)}><CalendarClock size={14}/>{organization.subscriptionEndsAtUtc && new Date(organization.subscriptionEndsAtUtc) > new Date() ? "Change period" : "Activate"}</button>{organization.subscriptionEndsAtUtc && new Date(organization.subscriptionEndsAtUtc) > new Date() && <button className="btn btn-secondary btn-small" onClick={() => subscription.mutate({ id: organization.id, active: false })}>End subscription</button>}<button className={`btn btn-small ${organization.isActive ? "btn-danger" : "btn-secondary"}`} onClick={() => toggle.mutate({ id: organization.id, enabled: !organization.isActive })}><Power size={14}/>{organization.isActive ? "Suspend account" : "Enable account"}</button><button className="btn btn-secondary btn-small" onClick={() => resetOwner(organization)}><KeyRound size={14}/>Reset password</button><button className="btn btn-danger btn-small" onClick={() => permanentlyDelete(organization)}><Trash2 size={14}/>Delete permanently</button></div></article>; })}</div>
    <section className="panel platform-admin-list"><div><span className="eyebrow">Platform security</span><h2>Full administrators</h2></div>{(administrators.data ?? []).map((admin) => <div key={admin.id}><span className="avatar">{admin.displayName.slice(0, 1)}</span><p><strong>{admin.displayName}</strong><small>{admin.email}</small></p><span className="badge success">Full access</span></div>)}</section>
    {createOpen && <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="modal-head"><h2>Create customer workspace</h2><button type="button" className="icon-button" onClick={() => setCreateOpen(false)} aria-label="Close"><X/></button></div><div className="form-grid"><label>Company name<input name="company" required placeholder="Acme Trading"/></label><label>Workspace slug<input name="slug" placeholder="acme-trading"/></label><label>First owner name<input name="owner" required/></label><label>Owner email<input name="email" type="email" required/></label><label>Initial activation days<input name="days" type="number" min="1" max="3650" defaultValue="30" required/></label><label>Temporary owner password<input name="password" type="password" minLength={8} required/><span className="muted">At least eight characters with a letter and number.</span></label></div>{create.error && <div className="error">{create.error.message}</div>}<div className="button-row" style={{ marginTop: 18 }}><button className="btn" disabled={create.isPending}>Create and activate</button><button type="button" className="btn btn-secondary" onClick={() => setCreateOpen(false)}>Cancel</button></div></form></div>}
    {adminOpen && <div className="modal-backdrop"><form className="modal" onSubmit={submitAdmin}><div className="modal-head"><h2>Add full platform administrator</h2><button type="button" className="icon-button" onClick={() => setAdminOpen(false)} aria-label="Close"><X/></button></div><div className="form-grid"><label>Full name<input name="name" required/></label><label>Email<input name="email" type="email" required/></label><label className="full">Temporary password<input name="password" type="password" minLength={8} required/></label></div>{createAdmin.error && <div className="error">{createAdmin.error.message}</div>}<div className="button-row" style={{ marginTop: 18 }}><button className="btn" disabled={createAdmin.isPending}>Create administrator</button><button type="button" className="btn btn-secondary" onClick={() => setAdminOpen(false)}>Cancel</button></div></form></div>}
  </Shell>;
}
