"use client";

import { FormEvent, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowRightLeft, Landmark, Scale, WalletCards } from "lucide-react";
import { Shell } from "@/components/shell";
import { api, money, queryString, User } from "@/lib/api";

type Balance = { id: string; name: string; provider: string; currencyCode: string; openingBalance: number; balanceLimit?: number; received: number; adjustments: number; currentBalance: number; lastReconciledAtUtc?: string; isActive: boolean };
type Entry = { id: string; walletId: string; walletName: string; type: string; amount: number; note?: string; occurredAtUtc: string };
type Operations = { balances: Balance[]; recent: Entry[] };
type Statement = { wallet: { id: string; name: string; currencyCode: string }; currentBalance: number; items: { id: string; type: string; amount: number; note?: string; occurredAtUtc: string }[]; total: number; page: number; totalPages: number };

export default function WalletOperationsPage() {
  const client = useQueryClient(); const [statementWallet, setStatementWallet] = useState(""); const [statementPage, setStatementPage] = useState(1); const me = useQuery({ queryKey: ["me"], queryFn: () => api<User>("/api/auth/me") }); const canManage = ["Owner", "Admin"].includes(me.data?.role ?? "");
  const operations = useQuery({ queryKey: ["wallet-operations"], queryFn: () => api<Operations>("/api/wallet-operations") });
  const statement = useQuery({ queryKey: ["wallet-statement", statementWallet, statementPage], queryFn: () => api<Statement>(`/api/wallet-operations/statement${queryString({ walletId: statementWallet, page: statementPage })}`), enabled: Boolean(statementWallet) });
  const mutate = useMutation({ mutationFn: ({ path, body }: { path: string; body: object }) => api(`/api/wallet-operations/${path}`, { method: "POST", body: JSON.stringify(body) }), onSuccess: () => { client.invalidateQueries({ queryKey: ["wallet-operations"] }); client.invalidateQueries({ queryKey: ["wallets"] }); } });
  function entry(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); mutate.mutate({ path: "entry", body: { walletId: form.get("walletId"), type: form.get("type"), amount: Number(form.get("amount")), note: form.get("note") } }); event.currentTarget.reset(); }
  function transfer(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); mutate.mutate({ path: "transfer", body: { fromWalletId: form.get("fromWalletId"), toWalletId: form.get("toWalletId"), amount: Number(form.get("amount")), note: form.get("note") } }); event.currentTarget.reset(); }
  function reconcile(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); mutate.mutate({ path: "reconcile", body: { walletId: form.get("walletId"), actualBalance: Number(form.get("actualBalance")), note: form.get("note") } }); }
  const active = (operations.data?.balances ?? []).filter((wallet) => wallet.isActive);
  return <Shell><div className="page-head"><div><span className="eyebrow">Financial control</span><h1>Balances & reconciliation</h1><p>Track opening balances, received payments, withdrawals, deposits, transfers, adjustments, and physical wallet checks.</p></div></div>
    {mutate.error && <div className="error">{mutate.error.message}</div>}{mutate.isSuccess && <div className="notice">Operation saved and balances recalculated.</div>}
    <div className="grid">{(operations.data?.balances ?? []).map((wallet) => <article className="card" key={wallet.id}><div className="card-top"><div className="card-icon"><WalletCards/></div><span className={`badge ${wallet.currentBalance < 0 ? "danger" : "success"}`}>{wallet.isActive ? "Active" : "Paused"}</span></div><h2>{wallet.name}</h2><p>{wallet.provider} · {wallet.currencyCode}</p><div className="balance-total">{money(wallet.currentBalance, wallet.currencyCode)}</div><p>Opening {money(wallet.openingBalance, wallet.currencyCode)} · Received {money(wallet.received, wallet.currencyCode)} · Other {money(wallet.adjustments, wallet.currencyCode)}</p>{wallet.balanceLimit && <><div className="progress"><span style={{ width: `${Math.min(100, Math.max(0, wallet.currentBalance / wallet.balanceLimit * 100))}%` }}/></div><small>{((wallet.currentBalance / wallet.balanceLimit) * 100).toFixed(0)}% of configured limit</small></>}<button className="btn btn-secondary btn-small" style={{ marginTop: 12 }} onClick={() => { setStatementWallet(wallet.id); setStatementPage(1); }}>View statement</button></article>)}</div>
    {statementWallet && <section className="panel" style={{ marginTop: 18 }}><div className="card-top"><div><span className="eyebrow">Complete statement</span><h2>{statement.data?.wallet.name ?? "Loading…"}</h2></div><strong>{statement.data ? money(statement.data.currentBalance, statement.data.wallet.currencyCode) : ""}</strong></div>{statement.error && <div className="error">{statement.error.message}</div>}<div className="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Description</th><th>Amount</th></tr></thead><tbody>{(statement.data?.items ?? []).map((row) => <tr key={`${row.type}-${row.id}`}><td>{new Date(row.occurredAtUtc).toLocaleString()}</td><td>{row.type}</td><td>{row.note ?? "—"}</td><td className={row.amount < 0 ? "negative" : "positive"}>{money(row.amount, statement.data?.wallet.currencyCode ?? "EGP")}</td></tr>)}</tbody></table></div><div className="pagination"><button className="btn btn-secondary btn-small" disabled={statementPage <= 1} onClick={() => setStatementPage((value) => value - 1)}>Previous</button><span>{statement.data?.total ?? 0} entries</span><button className="btn btn-secondary btn-small" disabled={statementPage >= (statement.data?.totalPages ?? 1)} onClick={() => setStatementPage((value) => value + 1)}>Next</button></div></section>}
    {canManage && <div className="grid operations-grid"><form className="panel" onSubmit={entry}><div className="card-icon"><Landmark/></div><h2>Manual wallet entry</h2><label>Wallet<select name="walletId" required><option value="">Choose wallet</option>{active.map((wallet) => <option key={wallet.id} value={wallet.id}>{wallet.name} · {wallet.currencyCode}</option>)}</select></label><label>Type<select name="type"><option>Withdrawal</option><option>Deposit</option><option>Adjustment</option></select></label><label>Amount<input name="amount" type="number" step="0.0001" required/></label><label>Note<textarea name="note" rows={2} required/></label><button className="btn" disabled={mutate.isPending}>Save entry</button></form>
      <form className="panel" onSubmit={transfer}><div className="card-icon"><ArrowRightLeft/></div><h2>Transfer between wallets</h2><label>From<select name="fromWalletId" required><option value="">Choose source</option>{active.map((wallet) => <option key={wallet.id} value={wallet.id}>{wallet.name} · {wallet.currencyCode}</option>)}</select></label><label>To<select name="toWalletId" required><option value="">Choose destination</option>{active.map((wallet) => <option key={wallet.id} value={wallet.id}>{wallet.name} · {wallet.currencyCode}</option>)}</select></label><label>Amount<input name="amount" type="number" min="0.0001" step="0.0001" required/></label><label>Note<textarea name="note" rows={2}/></label><button className="btn" disabled={mutate.isPending}>Record transfer</button></form>
      <form className="panel" onSubmit={reconcile}><div className="card-icon"><Scale/></div><h2>Reconcile actual balance</h2><label>Wallet<select name="walletId" required><option value="">Choose wallet</option>{active.map((wallet) => <option key={wallet.id} value={wallet.id}>{wallet.name} · expected {money(wallet.currentBalance, wallet.currencyCode)}</option>)}</select></label><label>Actual provider balance<input name="actualBalance" type="number" step="0.0001" required/></label><label>Note<textarea name="note" rows={2}/></label><button className="btn" disabled={mutate.isPending}>Save reconciliation</button></form></div>}
    <section className="panel"><span className="eyebrow">Manual activity</span><h2>Recent wallet operations</h2><div className="table-wrap"><table><thead><tr><th>Date</th><th>Wallet</th><th>Type</th><th>Amount</th><th>Note</th></tr></thead><tbody>{(operations.data?.recent ?? []).map((row) => { const wallet = operations.data?.balances.find((item) => item.id === row.walletId); return <tr key={row.id}><td>{new Date(row.occurredAtUtc).toLocaleString()}</td><td>{row.walletName}</td><td>{row.type}</td><td className={row.amount < 0 ? "negative" : "positive"}>{money(row.amount, wallet?.currencyCode ?? "EGP")}</td><td>{row.note ?? "—"}</td></tr>; })}</tbody></table></div></section>
  </Shell>;
}
