"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, Bell, ChevronRight, ClipboardList, Clock3, KeyRound, Languages, LockKeyhole, ShieldCheck, UserRound } from "lucide-react";
import { Shell } from "@/components/shell";
import { api, User } from "@/lib/api";
import { LanguageToggle } from "@/components/i18n";

type Preferences = { everyReceipt: boolean; minimumAmount?: number; dailySummary: boolean; deviceOffline: boolean };
type Workspace = { timeZoneId: string; maskSensitiveMessages: boolean; requireReceiptConfirmation: boolean };
type MfaSetup = { secretKey: string; authenticatorUri: string };

export default function SettingsPage() {
  const client = useQueryClient(); const [mfa, setMfa] = useState<MfaSetup>(); const [recoveryCodes, setRecoveryCodes] = useState<string[]>([]);
  const me = useQuery({ queryKey: ["me"], queryFn: () => api<User>("/api/auth/me") }); const isAdmin = ["Owner", "Admin"].includes(me.data?.role ?? "");
  const preference = useQuery({ queryKey: ["notification-preferences"], queryFn: () => api<Preferences>("/api/settings/notifications") });
  const workspace = useQuery({ queryKey: ["workspace-settings"], queryFn: () => api<Workspace>("/api/settings/workspace") });
  const savePreference = useMutation({ mutationFn: (body: Preferences) => api("/api/settings/notifications", { method: "PUT", body: JSON.stringify(body) }), onSuccess: () => client.invalidateQueries({ queryKey: ["notification-preferences"] }) });
  const saveWorkspace = useMutation({ mutationFn: (body: Workspace) => api("/api/settings/workspace", { method: "PUT", body: JSON.stringify(body) }), onSuccess: () => client.invalidateQueries({ queryKey: ["workspace-settings"] }) });
  const saveAccount = useMutation({ mutationFn: (body: object) => api("/api/auth/account", { method: "PUT", body: JSON.stringify(body) }), onSuccess: () => client.invalidateQueries({ queryKey: ["me"] }) });
  const security = useMutation({ mutationFn: ({ path, body }: { path: string; body?: object }) => api<{ recoveryCodes?: string[] }>(`/api/auth/${path}`, { method: "POST", body: body ? JSON.stringify(body) : undefined }) });
  function notifications(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); savePreference.mutate({ everyReceipt: form.get("every") === "on", minimumAmount: Number(form.get("minimum")) || undefined, dailySummary: form.get("daily") === "on", deviceOffline: form.get("offline") === "on" }); }
  function account(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); saveAccount.mutate({ displayName: form.get("name"), email: form.get("email"), currentPassword: form.get("currentPassword"), newPassword: form.get("newPassword") || null }); }
  function workspaceSave(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); saveWorkspace.mutate({ timeZoneId: String(form.get("timeZone")), maskSensitiveMessages: form.get("mask") === "on", requireReceiptConfirmation: form.get("confirmation") === "on" }); }
  async function setupMfa() { try { setMfa(await api<MfaSetup>("/api/auth/mfa/setup", { method: "POST" })); } catch (error) { window.alert((error as Error).message); } }
  function confirmMfa(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const code = String(new FormData(event.currentTarget).get("code")); security.mutate({ path: "mfa/confirm", body: { code } }, { onSuccess: (result) => { setRecoveryCodes(result.recoveryCodes ?? []); setMfa(undefined); client.invalidateQueries({ queryKey: ["me"] }); } }); }
  function disableMfa() { const password = window.prompt("Enter your current password to disable two-factor authentication:"); if (password) security.mutate({ path: "mfa/disable", body: { password } }, { onSuccess: () => client.invalidateQueries({ queryKey: ["me"] }) }); }

  return <Shell><div className="page-head"><div><span className="eyebrow">Workspace & security</span><h1>Settings</h1><p>Manage your profile, account security, reporting time zone, privacy, and operational alerts.</p></div></div>
    <div className="grid two settings-grid"><section className="panel"><div className="card-icon"><Languages/></div><h2>Language</h2><p>Interface language</p><LanguageToggle/></section><form className="panel" onSubmit={account} key={me.data?.email}><div className="card-icon"><UserRound/></div><h2>My account</h2><label>Display name<input name="name" defaultValue={me.data?.displayName} required/></label><label>Email<input name="email" type="email" defaultValue={me.data?.email} required/></label><label>Current password<input name="currentPassword" type="password" required/></label><label>New password (optional)<input name="newPassword" type="password" minLength={8} autoComplete="new-password"/></label><button className="btn" disabled={saveAccount.isPending}>{saveAccount.isPending ? "Saving…" : "Save account"}</button><Result mutation={saveAccount}/></form>
      <form className="panel" onSubmit={notifications} key={JSON.stringify(preference.data)}><div className="card-icon"><Bell/></div><h2>My notification rules</h2><label className="checkbox"><input type="checkbox" name="every" defaultChecked={preference.data?.everyReceipt ?? true}/>Notify me for every receipt</label><label>Only at or above<input type="number" min="0" step="0.01" name="minimum" defaultValue={preference.data?.minimumAmount ?? ""} placeholder="No minimum"/></label><label className="checkbox"><input type="checkbox" name="daily" defaultChecked={preference.data?.dailySummary ?? true}/>Daily operational summary</label><label className="checkbox"><input type="checkbox" name="offline" defaultChecked={preference.data?.deviceOffline ?? true}/>Device offline alerts</label><button className="btn" disabled={savePreference.isPending}>Save notifications</button><Result mutation={savePreference}/></form>
      <section className="panel"><div className="card-icon"><LockKeyhole/></div><h2>Account security</h2><p>Two-factor authentication protects your account even if a password is exposed.</p>{me.data?.twoFactorEnabled ? <button className="btn btn-danger" onClick={disableMfa}>Disable two-factor authentication</button> : <button className="btn" onClick={setupMfa}><ShieldCheck size={17}/>Enable two-factor authentication</button>}<button className="btn btn-secondary" style={{ marginTop: 10 }} onClick={() => security.mutate({ path: "revoke-other-sessions" }, { onSuccess: () => window.alert("Other sessions have been revoked.") })}><KeyRound size={17}/>Sign out other sessions</button>{mfa && <form onSubmit={confirmMfa} className="mfa-box"><strong>1. Add this key to your authenticator app</strong><code>{mfa.secretKey}</code><label>2. Enter the six-digit code<input name="code" inputMode="numeric" pattern="[0-9]{6}" required/></label><button className="btn">Confirm two-factor</button></form>}{recoveryCodes.length > 0 && <div className="notice"><strong>Save these one-time recovery codes now:</strong><code>{recoveryCodes.join("\n")}</code></div>}<Result mutation={security}/></section>
      {isAdmin && <form className="panel" onSubmit={workspaceSave} key={JSON.stringify(workspace.data)}><div className="card-icon"><Clock3/></div><h2>Workspace controls</h2><label>Reporting time zone<select name="timeZone" defaultValue={workspace.data?.timeZoneId ?? "Africa/Cairo"}><option value="Africa/Cairo">Africa/Cairo</option><option value="UTC">UTC</option><option value="Asia/Riyadh">Asia/Riyadh</option><option value="Asia/Dubai">Asia/Dubai</option></select></label><label className="checkbox"><input type="checkbox" name="mask" defaultChecked={workspace.data?.maskSensitiveMessages}/>Mask phone numbers in original SMS messages</label><label className="checkbox setting-toggle"><input type="checkbox" name="confirmation" defaultChecked={workspace.data?.requireReceiptConfirmation}/><span><strong>Require payment confirmation</strong><small>New payments stay pending until an authorized team member confirms them. Reports and balances count confirmed payments only.</small></span></label><p className="muted">Turning this off automatically confirms any remaining pending payments.</p><button className="btn" disabled={saveWorkspace.isPending}>Save workspace</button><Result mutation={saveWorkspace}/></form>}
      {(isAdmin || me.data?.canManageDevices) && <section className="panel advanced-tools"><div className="card-icon"><ShieldCheck/></div><h2>Advanced tools</h2><p>Diagnostics and accountability tools for administrators.</p>{me.data?.canManageDevices || isAdmin ? <Link href="/capture-health"><span><Activity/><strong>Capture inbox<small>Inspect unmatched or duplicate SMS captures</small></strong></span><ChevronRight/></Link> : null}{isAdmin && <Link href="/audit"><span><ClipboardList/><strong>Audit trail<small>Review account, permission, and financial actions</small></strong></span><ChevronRight/></Link>}</section>}
    </div>
  </Shell>;
}

function Result({ mutation }: { mutation: { isSuccess: boolean; error: Error | null } }) { return <>{mutation.error && <div className="error">{mutation.error.message}</div>}{mutation.isSuccess && <div className="notice">Saved successfully.</div>}</>; }
